### PR TITLE
feat: implement `Move to file` code action

### PR DESCRIPTION
**Pull request by pmizio**
TODO:

- [ ] config option to pass other telescope builtin pickers (default `find_files`)
- [ ]  config option to pass custom function as file picker(allow to use other things than telescope)

### CODE REVIEW

**Comment by mmirus** [comment]
Hello! Is there any plan to merge this? I'm happy to help test if that would be useful.

**Comment by unphased** [comment]
It works great! there is just one issue where if the target file does not have a newline at the end, stuff you're moving doesnt land in there. That's the main big bug i found over the past couple months daily driving this (i use it in bursts once every few weeks).

**Comment by KostkaBrukowa** [comment]
@unphased I've might have fixed this problem. Can you check if the fix works for you?

**Comment by kloczewiak** [comment]
Any update? Can we get this merged?

**Comment by unphased** [comment]
I think we should go ahead with this. I tried to look up the `vim.lsp.util.apply_workspace_edit` API but I can't find any more information about what a `WorkspaceEdit` is...

**Pull request merged**
