### PR TITLE
feat: search for tsserver in PATH and mason registry

### PR DESCRIPTION
**Pull request by pmizio**

### CODE REVIEW

**Review by megalithic — APPROVED** [review]
Yes! This fixes it for me as well. Thanks @pmizio!

**Comment by perrin4869** [comment]
this PR seems to have broken `typescript-tools.nvim` for me, I am getting errors when opening js/ts files:

```
Error executing luv callback:
...ult/start/mason.nvim/lua/mason-registry/sources/init.lua:77: attempt to index upvalue 'opts' (a nil value)
stack traceback:
	[builtin#36]: at 0x7fed2035ef00
Error executing luv callback:
...ult/start/mason.nvim/lua/mason-registry/sources/init.lua:77: attempt to index upvalue 'opts' (a nil value)
stack traceback:
	[builtin#36]: at 0x7fed2035ef00
Error executing luv callback:
cannot resume dead coroutine
stack traceback:
	[builtin#36]: at 0x7fed2035ef00
Error executing luv callback:
cannot resume dead coroutine
stack traceback:
	[builtin#36]: at 0x7fed2035ef00
```

I am using `mason` and `mason-lspconfig`, in addition to `typescript-tools`
I am using the [`file` type registry](https://github.com/williamboman/mason.nvim/pull/1457/files), so it may have something to do with that, but I haven't investigated enough yet. 
I can try and keep digging more into it, but using `mason`'s registry is a bit trickier than the API might suggest.
I think you'd need to call the [`registry.refresh`](https://github.com/williamboman/mason.nvim/issues/1424#issuecomment-1682712706) method before being able to call `mason_registry.get_package("typescript-language-server")` safely... but honestly, this seems like an anti-pattern anyways, since mason works by adding the binary to the PATH. I think the better alternative would be to try to execute `tsserver` as is, in case it cannot be found inside `node_modules`, etc, and leave mason alone to do its thing...
I'll dig a bit more into exactly what's going wrong here, but I think that's the better approach ^^;;

**Comment by perrin4869** [comment]
So yeah, the problem is that when calling `mason_registry.get_package("typescript-language-server")`, [`mason` will iterate](https://github.com/williamboman/mason.nvim/blob/d66c60e17dd6fd8165194b1d14d21f7eb2c1697a/lua/mason-registry/init.lua#L73) over the [installed registries](https://github.com/williamboman/mason.nvim/blob/d66c60e17dd6fd8165194b1d14d21f7eb2c1697a/lua/mason-registry/sources/init.lua#L78), and unfortunately, the `file` type registry will not report itself as being installed until `require("mason-registry").refresh(function () end)` has been called. Calling `refresh` from inside this plugin would make `get_tsserver_from_mason` async and quite slow... but yeah, I think that retrieving the path from the mason registry is not the way to go anyways

@williamboman do you have any opinions on this topic?

**Comment by williamboman** [comment]
Is the existence of the `tsserver` executable enough, or does typescript-tools.nvim need to reach into `node_modules/`? If an executable is enough, then there shouldn't be a need to have any special interactions with Mason - `vim.fn.executable("tsserver")` would resolve to Mason's linked executable (once https://github.com/mason-org/mason-registry/pull/2845 lands).

The `typescript-language-server` package, which seems to be used now, contains a fixed version of Typescript in order for the LSP to function, so relying on that `typescript` installation would be unstable should that dependency ever be removed or changed.

**Comment by perrin4869** [comment]
So I think `typescript-tools` defaults to using whichever `tsserver` is installed in the current project you're working on, then it wants to fall back to using a `PATH` available `tsserver`, possibly provided by `meson`, so I don't think a stable path is actually needed. The `vim.fn.executable("tsserver")` is a great tip, thanks! I was wondering if there was a way to resolve the `PATH` easily

**Pull request merged**
